### ISSUE TITLE
不兼容WHMCS7.2.3

### ISSUE THREAD

**Issue by hans362** [BlueAirTechGroup/EasyPanelModule-For-Whmcs#1]
放进modules/servers文件夹后WHMCS服务器配置页面直接崩溃，出现Opps...There’s something wrong...的提示。我的PHP版本为7.0

**Comment by realquantumcookie** [comment]
收到, 目前手头没有WHMCS7.2.3的安装包, 可能无法测试. 但是我会看下把代码改了.

**Comment by realquantumcookie** [comment]
您好, 根据测试, 本EasyPanel模块完美兼容WHMCS7.2.3.
然而, 当第二次测试环境为PHP7.1时, 由于测试机器ionCube版本过低, 无法进行测试.
本模块使用方法为将此分支下的"Easypanel"文件夹整个放在modules/server, 而这个easypanel文件夹中除了俩个.php文件没有其他文件, 请不要把readme.md这些文件一起放在你的服务器中.
